svr_config:
  name: "relationsvr"
  host: "127.0.0.1"
  port: 8001
  user_svr_name: "usersvr"

redis:
  host: "127.0.0.1"
  password: "password"
  db: 0
  port: 6379
  PoolSize: 10

mysql:
  host: "127.0.0.1"
  port: "3306"
  database: "douflick"
  username: "root"
  password: "root"
  max_idle_conn: 10
  max_open_conn: 100
  max_idle_time: 30

log:
  level: "debug"
  log_path: "../../log/relationsvr/"
  file_name: "relationsvr.log"
  max_size: 200
  max_age: 30
  max_backups: 7

consul:
  host: "127.0.0.1"
  port: 8500
  tags:
    - "relationsvr"

