// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: user.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	UserService_CheckPassWord_FullMethodName           = "/UserService/CheckPassWord"
	UserService_GetUserInfo_FullMethodName             = "/UserService/GetUserInfo"
	UserService_GetUserInfoList_FullMethodName         = "/UserService/GetUserInfoList"
	UserService_Register_FullMethodName                = "/UserService/Register"
	UserService_GetUserInfoDict_FullMethodName         = "/UserService/GetUserInfoDict"
	UserService_CacheChangeUserCount_FullMethodName    = "/UserService/CacheChangeUserCount"
	UserService_CacheGetAuthor_FullMethodName          = "/UserService/CacheGetAuthor"
	UserService_UpdateMyFavouritedCount_FullMethodName = "/UserService/UpdateMyFavouritedCount"
	UserService_UpdateMyFavouriteCount_FullMethodName  = "/UserService/UpdateMyFavouriteCount"
	UserService_UpdateMyFollowCount_FullMethodName     = "/UserService/UpdateMyFollowCount"
	UserService_UpdateMyFollowerCount_FullMethodName   = "/UserService/UpdateMyFollowerCount"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	CheckPassWord(ctx context.Context, in *CheckPassWordRequest, opts ...grpc.CallOption) (*CheckPassWordResponse, error)
	GetUserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error)
	GetUserInfoList(ctx context.Context, in *UserInfoListRequest, opts ...grpc.CallOption) (*UserInfoListResponse, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	GetUserInfoDict(ctx context.Context, in *UserInfoDictRequest, opts ...grpc.CallOption) (*UserInfoDictResponse, error)
	CacheChangeUserCount(ctx context.Context, in *CacheChangeUserCountRequest, opts ...grpc.CallOption) (*CacheChangeUserCountResponse, error)
	CacheGetAuthor(ctx context.Context, in *CacheGetAuthorRequest, opts ...grpc.CallOption) (*CacheGetAuthorResponse, error)
	// 数据库更新
	// 更新我的获赞数
	UpdateMyFavouritedCount(ctx context.Context, in *UpdateMyFavouritedCountRequest, opts ...grpc.CallOption) (*UpdateMyFavouritedCountResponse, error)
	// 更新我喜欢的视频数
	UpdateMyFavouriteCount(ctx context.Context, in *UpdateMyFavouriteCountRequest, opts ...grpc.CallOption) (*UpdateMyFavouriteCountResponse, error)
	// 更新我的关注数
	UpdateMyFollowCount(ctx context.Context, in *UpdateMyFollowCountRequest, opts ...grpc.CallOption) (*UpdateMyFollowCountResponse, error)
	// 更新我的粉丝数
	UpdateMyFollowerCount(ctx context.Context, in *UpdateMyFollowerCountRequest, opts ...grpc.CallOption) (*UpdateMyFollowerCountResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CheckPassWord(ctx context.Context, in *CheckPassWordRequest, opts ...grpc.CallOption) (*CheckPassWordResponse, error) {
	out := new(CheckPassWordResponse)
	err := c.cc.Invoke(ctx, UserService_CheckPassWord_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	out := new(UserInfoResponse)
	err := c.cc.Invoke(ctx, UserService_GetUserInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserInfoList(ctx context.Context, in *UserInfoListRequest, opts ...grpc.CallOption) (*UserInfoListResponse, error) {
	out := new(UserInfoListResponse)
	err := c.cc.Invoke(ctx, UserService_GetUserInfoList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, UserService_Register_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserInfoDict(ctx context.Context, in *UserInfoDictRequest, opts ...grpc.CallOption) (*UserInfoDictResponse, error) {
	out := new(UserInfoDictResponse)
	err := c.cc.Invoke(ctx, UserService_GetUserInfoDict_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CacheChangeUserCount(ctx context.Context, in *CacheChangeUserCountRequest, opts ...grpc.CallOption) (*CacheChangeUserCountResponse, error) {
	out := new(CacheChangeUserCountResponse)
	err := c.cc.Invoke(ctx, UserService_CacheChangeUserCount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CacheGetAuthor(ctx context.Context, in *CacheGetAuthorRequest, opts ...grpc.CallOption) (*CacheGetAuthorResponse, error) {
	out := new(CacheGetAuthorResponse)
	err := c.cc.Invoke(ctx, UserService_CacheGetAuthor_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateMyFavouritedCount(ctx context.Context, in *UpdateMyFavouritedCountRequest, opts ...grpc.CallOption) (*UpdateMyFavouritedCountResponse, error) {
	out := new(UpdateMyFavouritedCountResponse)
	err := c.cc.Invoke(ctx, UserService_UpdateMyFavouritedCount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateMyFavouriteCount(ctx context.Context, in *UpdateMyFavouriteCountRequest, opts ...grpc.CallOption) (*UpdateMyFavouriteCountResponse, error) {
	out := new(UpdateMyFavouriteCountResponse)
	err := c.cc.Invoke(ctx, UserService_UpdateMyFavouriteCount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateMyFollowCount(ctx context.Context, in *UpdateMyFollowCountRequest, opts ...grpc.CallOption) (*UpdateMyFollowCountResponse, error) {
	out := new(UpdateMyFollowCountResponse)
	err := c.cc.Invoke(ctx, UserService_UpdateMyFollowCount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateMyFollowerCount(ctx context.Context, in *UpdateMyFollowerCountRequest, opts ...grpc.CallOption) (*UpdateMyFollowerCountResponse, error) {
	out := new(UpdateMyFollowerCountResponse)
	err := c.cc.Invoke(ctx, UserService_UpdateMyFollowerCount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility
type UserServiceServer interface {
	CheckPassWord(context.Context, *CheckPassWordRequest) (*CheckPassWordResponse, error)
	GetUserInfo(context.Context, *UserInfoRequest) (*UserInfoResponse, error)
	GetUserInfoList(context.Context, *UserInfoListRequest) (*UserInfoListResponse, error)
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	GetUserInfoDict(context.Context, *UserInfoDictRequest) (*UserInfoDictResponse, error)
	CacheChangeUserCount(context.Context, *CacheChangeUserCountRequest) (*CacheChangeUserCountResponse, error)
	CacheGetAuthor(context.Context, *CacheGetAuthorRequest) (*CacheGetAuthorResponse, error)
	// 数据库更新
	// 更新我的获赞数
	UpdateMyFavouritedCount(context.Context, *UpdateMyFavouritedCountRequest) (*UpdateMyFavouritedCountResponse, error)
	// 更新我喜欢的视频数
	UpdateMyFavouriteCount(context.Context, *UpdateMyFavouriteCountRequest) (*UpdateMyFavouriteCountResponse, error)
	// 更新我的关注数
	UpdateMyFollowCount(context.Context, *UpdateMyFollowCountRequest) (*UpdateMyFollowCountResponse, error)
	// 更新我的粉丝数
	UpdateMyFollowerCount(context.Context, *UpdateMyFollowerCountRequest) (*UpdateMyFollowerCountResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (UnimplementedUserServiceServer) CheckPassWord(context.Context, *CheckPassWordRequest) (*CheckPassWordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckPassWord not implemented")
}
func (UnimplementedUserServiceServer) GetUserInfo(context.Context, *UserInfoRequest) (*UserInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedUserServiceServer) GetUserInfoList(context.Context, *UserInfoListRequest) (*UserInfoListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfoList not implemented")
}
func (UnimplementedUserServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedUserServiceServer) GetUserInfoDict(context.Context, *UserInfoDictRequest) (*UserInfoDictResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfoDict not implemented")
}
func (UnimplementedUserServiceServer) CacheChangeUserCount(context.Context, *CacheChangeUserCountRequest) (*CacheChangeUserCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CacheChangeUserCount not implemented")
}
func (UnimplementedUserServiceServer) CacheGetAuthor(context.Context, *CacheGetAuthorRequest) (*CacheGetAuthorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CacheGetAuthor not implemented")
}
func (UnimplementedUserServiceServer) UpdateMyFavouritedCount(context.Context, *UpdateMyFavouritedCountRequest) (*UpdateMyFavouritedCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMyFavouritedCount not implemented")
}
func (UnimplementedUserServiceServer) UpdateMyFavouriteCount(context.Context, *UpdateMyFavouriteCountRequest) (*UpdateMyFavouriteCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMyFavouriteCount not implemented")
}
func (UnimplementedUserServiceServer) UpdateMyFollowCount(context.Context, *UpdateMyFollowCountRequest) (*UpdateMyFollowCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMyFollowCount not implemented")
}
func (UnimplementedUserServiceServer) UpdateMyFollowerCount(context.Context, *UpdateMyFollowerCountRequest) (*UpdateMyFollowerCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMyFollowerCount not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_CheckPassWord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPassWordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CheckPassWord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CheckPassWord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CheckPassWord(ctx, req.(*CheckPassWordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserInfo(ctx, req.(*UserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserInfoList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserInfoList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUserInfoList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserInfoList(ctx, req.(*UserInfoListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserInfoDict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoDictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserInfoDict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUserInfoDict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserInfoDict(ctx, req.(*UserInfoDictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CacheChangeUserCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CacheChangeUserCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CacheChangeUserCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CacheChangeUserCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CacheChangeUserCount(ctx, req.(*CacheChangeUserCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CacheGetAuthor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CacheGetAuthorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CacheGetAuthor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CacheGetAuthor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CacheGetAuthor(ctx, req.(*CacheGetAuthorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateMyFavouritedCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMyFavouritedCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateMyFavouritedCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateMyFavouritedCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateMyFavouritedCount(ctx, req.(*UpdateMyFavouritedCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateMyFavouriteCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMyFavouriteCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateMyFavouriteCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateMyFavouriteCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateMyFavouriteCount(ctx, req.(*UpdateMyFavouriteCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateMyFollowCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMyFollowCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateMyFollowCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateMyFollowCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateMyFollowCount(ctx, req.(*UpdateMyFollowCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateMyFollowerCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMyFollowerCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateMyFollowerCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateMyFollowerCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateMyFollowerCount(ctx, req.(*UpdateMyFollowerCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckPassWord",
			Handler:    _UserService_CheckPassWord_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _UserService_GetUserInfo_Handler,
		},
		{
			MethodName: "GetUserInfoList",
			Handler:    _UserService_GetUserInfoList_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _UserService_Register_Handler,
		},
		{
			MethodName: "GetUserInfoDict",
			Handler:    _UserService_GetUserInfoDict_Handler,
		},
		{
			MethodName: "CacheChangeUserCount",
			Handler:    _UserService_CacheChangeUserCount_Handler,
		},
		{
			MethodName: "CacheGetAuthor",
			Handler:    _UserService_CacheGetAuthor_Handler,
		},
		{
			MethodName: "UpdateMyFavouritedCount",
			Handler:    _UserService_UpdateMyFavouritedCount_Handler,
		},
		{
			MethodName: "UpdateMyFavouriteCount",
			Handler:    _UserService_UpdateMyFavouriteCount_Handler,
		},
		{
			MethodName: "UpdateMyFollowCount",
			Handler:    _UserService_UpdateMyFollowCount_Handler,
		},
		{
			MethodName: "UpdateMyFollowerCount",
			Handler:    _UserService_UpdateMyFollowerCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
