name: Docker Build and Push

on:
  push:
    tags:
      - "*dockerfile*"

env:
  IMAGE_NAME: douflick_

jobs:
  docker_images_build_and_push:
    runs-on: ubuntu-latest

    steps:
#      - name: Wait for Go build to finish
#        run: sleep 60
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
#
#      - name: Get version
#        id: version
#        run: echo "::set-output name=version::$(git describe --tags)"

      - name: Parse DockerImagesName
        id: version
        run: |
          tag_name=$(git describe --tags)
          image_name=${tag_name#*_}
          echo "::set-output name=image_name::$image_name"
#git tag dockerfile_videosvr
      - name: Cd Dir
        run: |
          cd server/${{ steps.version.outputs.image_name }}
          pwd

      - name: Build Docker image
        run: |
          apt-get update && apt-get install -y ca-certificates
          pwd
          docker build -t fatataosu/${{ env.IMAGE_NAME }}${{ steps.version.outputs.image_name }} -f ./server/${{ steps.version.outputs.image_name }}/Dockerfile .

      - name: Push Docker image
        if: success()
        run: |
          docker images
          docker push fatataosu/${{ env.IMAGE_NAME }}${{ steps.version.outputs.image_name }}
